### PR TITLE
Add Uniswap v3 to all supply and exposure queries

### PR DESCRIPTION
**Pull request by deepsp94**

### CODE REVIEW

**Comment by deepsp94** [comment]
@josephd8 i've updated the `eth2xfli-supply-breakdown` file again. I know this has already been updated and approved before, but I've made a couple of changes on top of that last version, as follows:
1. Now we get all uniswap v3 pools of eth2x-fli automatically. Not just the eth2xfli-weth pool.
2. Changed the logic of the `mint_burn_swap` CTE. I think my last version would have been problematic if there were multiple mints/burns/swaps in the same minute. The numbers haven't changed due to making this change, still good to have caught and fixed this potential problem.
Will replicate this same logic for DPI, MVI and ETH2x-FLI as well. Happy for you to review this in the meantime, thanks!

**Comment by deepsp94** [comment]
Likewise, updated the logic in `eth2xfli-address-exposure.sql` so that all uniswap v3 pools with ETH2x-FLI are accounted for automatically

**Comment by deepsp94** [comment]
All done @josephd8

**Comment by josephd8** [comment]
@deepsp94 - I think we should hold off on merging this for now and work on the next iteration. It will be quite a bit of work to get everything built into the dashboards, and I don't think it is worth doing all of that work twice if this only gets us part of the way there.

Thanks for all of your work here - I know this hasn't been easy to figure out. Let's touch base (maybe a call on Wednesday?) and determine the next steps.

**Pull request closed without merging**
